{{- if .Values.tnsApiKeySecret.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tnsApiKeySecret.name }}
{{ include "tnsplugin.labels" . | indent 2 }}
type: Opaque
data:
  apiKey: {{ .Values.tnsApiKeySecret.apiKey | b64enc | indent 2 }}
{{- end }}