---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: {{ .Values.driver.name }}
{{ include "tnsplugin.labels" . | indent 2 }}
spec:
  attachRequired: false
  volumeLifecycleModes:
    - Persistent
  {{- if .Values.feature.enableInlineVolume}}
    - Ephemeral
  {{- end}}
  {{- if .Values.feature.enableFSGroupPolicy}}
  fsGroupPolicy: File
  {{- end}}
