{{- if .Values.volumeSnapshotClass.create }}
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: {{ .Values.volumeSnapshotClass.name }}
{{ include "tnsplugin.labels" . | indent 2 }}
driver: {{ .Values.driver.name }}
deletionPolicy: {{ .Values.volumeSnapshotClass.deletionPolicy }}
{{- with .Values.volumeSnapshotClass.parameters }}
parameters:
{{ toYaml . | indent 2 }}
{{- end }}
{{- end }}
