{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.controller }}
  namespace: {{ .Release.Namespace }}
{{ include "tnsplugin.labels" . | indent 2 }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.node }}
  namespace: {{ .Release.Namespace }}
{{ include "tnsplugin.labels" . | indent 2 }}
---
{{- end }}
